#!/usr/bin/env bash
set -euo pipefail

RUNTIME_USER="admin"
PYTHON_BIN="${PYTHON_BIN:-python3}"
INSTALL_ROOT="/opt/wp-guardian"
VENV_DIR="$INSTALL_ROOT/venv"
VENV_OLD="$INSTALL_ROOT/venv.old"
CONFIG_FILE="/etc/wp-guardian/guardian.toml"
BACKUP_DIR="/home/admin/private-backups/wp-guardian"

if [[ ${EUID} -ne 0 ]]; then
  echo "Run the installer with sudo/root privileges" >&2
  exit 1
fi

if ! id "$RUNTIME_USER" >/dev/null 2>&1; then
  echo "Required runtime user does not exist: $RUNTIME_USER" >&2
  exit 1
fi

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  echo "Python interpreter not found: $PYTHON_BIN" >&2
  exit 1
fi

RUNTIME_GROUP="$(id -gn "$RUNTIME_USER")"
RUNTIME_HOME="$(getent passwd "$RUNTIME_USER" | cut -d: -f6)"
PYTHON_VERSION="$($PYTHON_BIN -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

if [[ -z "$RUNTIME_HOME" || ! -d "$RUNTIME_HOME" ]]; then
  echo "Runtime home directory is invalid for $RUNTIME_USER: $RUNTIME_HOME" >&2
  exit 1
fi

install -d -o root -g root -m 0755 "$INSTALL_ROOT"
rm -rf "$VENV_OLD"

# Console scripts generated by pip contain an absolute interpreter path in the
# shebang. Therefore the venv must be created at its final path and must never
# be renamed after package installation.
if [[ -d "$VENV_DIR" ]]; then
  mv "$VENV_DIR" "$VENV_OLD"
fi

restore_previous_install() {
  rm -rf "$VENV_DIR"
  if [[ -d "$VENV_OLD" ]]; then
    mv "$VENV_OLD" "$VENV_DIR"
  fi
}
trap restore_previous_install ERR

if ! "$PYTHON_BIN" -m venv "$VENV_DIR"; then
  cat >&2 <<EOF
Unable to create a Python virtual environment.

On Debian/Ubuntu install the matching venv package:
  sudo apt update
  sudo apt install -y python${PYTHON_VERSION}-venv

If the version-specific package is unavailable, use:
  sudo apt install -y python3-venv

Then run this installer again.
EOF
  exit 1
fi

# Use the normal PEP 517 build flow. pyproject.toml declares setuptools and
# wheel as build requirements, so pip creates an isolated build environment.
if ! "$VENV_DIR/bin/python" -m pip install .; then
  cat >&2 <<'EOF'
Unable to build/install softico-wp-guardian.

Check that the server can reach the configured Python package index. The build
requires setuptools and wheel, declared in pyproject.toml.
EOF
  exit 1
fi

# Verify the generated launcher before removing the rollback copy.
if ! "$VENV_DIR/bin/wp-guardian" --version >/dev/null; then
  echo "Installed wp-guardian launcher failed its smoke test" >&2
  exit 1
fi

rm -rf "$VENV_OLD"
trap - ERR

ln -sfn "$VENV_DIR/bin/wp-guardian" /usr/local/bin/wp-guardian

install -d -o root -g "$RUNTIME_GROUP" -m 0750 /etc/wp-guardian
install -d -o "$RUNTIME_USER" -g "$RUNTIME_GROUP" -m 0750 \
  /var/lib/wp-guardian \
  /var/lib/wp-guardian/reports
install -d -o "$RUNTIME_USER" -g "$RUNTIME_GROUP" -m 0700 \
  "$RUNTIME_HOME/private-backups" \
  "$BACKUP_DIR"

if [[ ! -f "$CONFIG_FILE" ]]; then
  install -o root -g "$RUNTIME_GROUP" -m 0640 \
    config/guardian.toml.example \
    "$CONFIG_FILE"
elif ! grep -Eq '^[[:space:]]*\[mail\][[:space:]]*$' "$CONFIG_FILE"; then
  # Preserve all existing settings while adding the mail section introduced by
  # newer versions. This migration is idempotent and never replaces the file.
  cat >> "$CONFIG_FILE" <<'EOF'

[mail]
enabled = true
recipients = ["skr@softico.ua"]
subject_prefix = "[WP Guardian]"
sendmail = "/usr/sbin/sendmail"
EOF
fi

if ! grep -Eq '^[[:space:]]*\[backup\][[:space:]]*$' "$CONFIG_FILE"; then
  cat >> "$CONFIG_FILE" <<'EOF'

[backup]
directory = "/home/admin/private-backups/wp-guardian"
timeout = 900
keep_last = 3
EOF
fi

if ! grep -Eq '^[[:space:]]*keep_last[[:space:]]*=' "$CONFIG_FILE"; then
  "$PYTHON_BIN" - "$CONFIG_FILE" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
lines = path.read_text(encoding="utf-8").splitlines()
try:
    section_index = next(
        index for index, line in enumerate(lines)
        if line.strip() == "[backup]"
    )
except StopIteration as exc:
    raise SystemExit("guardian.toml is missing the required [backup] section") from exc

insert_at = len(lines)
for index in range(section_index + 1, len(lines)):
    if lines[index].strip().startswith("["):
        insert_at = index
        break
lines.insert(insert_at, "keep_last = 3")
path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
PY
fi

if ! grep -Eq '^[[:space:]]*retention_business_days[[:space:]]*=' "$CONFIG_FILE"; then
  # Add the retention setting inside [general] without replacing any existing
  # configuration. The Python migration is used instead of brittle line-based
  # editing so it also works when max_scan_files is absent or reordered.
  "$PYTHON_BIN" - "$CONFIG_FILE" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
lines = text.splitlines()

try:
    general_index = next(
        index for index, line in enumerate(lines)
        if line.strip() == "[general]"
    )
except StopIteration as exc:
    raise SystemExit("guardian.toml is missing the required [general] section") from exc

insert_at = len(lines)
for index in range(general_index + 1, len(lines)):
    if lines[index].strip().startswith("["):
        insert_at = index
        break

lines.insert(insert_at, "retention_business_days = 3")
path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
PY
fi

chown root:"$RUNTIME_GROUP" "$CONFIG_FILE"
chmod 0640 "$CONFIG_FILE"

install -o root -g root -m 0644 \
  systemd/wp-guardian.service \
  /etc/systemd/system/wp-guardian.service
install -o root -g root -m 0644 \
  systemd/wp-guardian-mail.service \
  /etc/systemd/system/wp-guardian-mail.service
install -o root -g root -m 0644 \
  systemd/wp-guardian.timer \
  /etc/systemd/system/wp-guardian.timer

systemctl daemon-reload

if [[ ! -x /usr/sbin/sendmail ]]; then
  echo "Warning: /usr/sbin/sendmail is unavailable; report email will fail until a sendmail-compatible local transport is installed." >&2
fi

# The service and timer are intentionally not enabled or started automatically.
echo "Installed with read-only audits, private backups and guarded single-component update workflow."
echo "Runtime account: $RUNTIME_USER:$RUNTIME_GROUP"
echo "Root is used only for installation and isolated local mail submission."
echo "Audits, backups and guarded update commands run as $RUNTIME_USER."
echo "Only an explicitly prepared inactive-plugin update can currently modify WordPress files."
echo "Successful systemd audits trigger wp-guardian-mail.service."
echo "Audit reports and SQLite run history are retained for 3 business days by default."
echo "Database backups retain the latest 3 completed copies per domain by default."
echo "Run as $RUNTIME_USER:"
echo "  sudo -u $RUNTIME_USER wp-guardian --config $CONFIG_FILE sites"
echo "  sudo -u $RUNTIME_USER wp-guardian --config $CONFIG_FILE audit --domain softico.ua"
echo "  sudo -u $RUNTIME_USER wp-guardian --config $CONFIG_FILE backup --domain softico.ua"
echo "  sudo -u $RUNTIME_USER wp-guardian --config $CONFIG_FILE update-plan --domain softico.ua"
echo "  sudo -u $RUNTIME_USER wp-guardian --config $CONFIG_FILE prepare-update --help"
echo "  sudo -u $RUNTIME_USER wp-guardian --config $CONFIG_FILE apply-update --help"
echo "  sudo -u $RUNTIME_USER wp-guardian --config $CONFIG_FILE send-report"
